development:
  adapter: postgresql
  database: tambo_development
  pool: 5
  username: postgres
  timeout: 5000

test:
  adapter: postgresql
  database: tambo_test
  pool: 5
  username: postgres
  timeout: 5000

production:
  adapter: postgresql
  database: tambo_production
  pool: 5
  username: postgres
  timeout: 5000
