# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a29ed19c9e4b7c9d8e6f27a7cd98269b4ad2e18fcfe9825713c6a681e36f06293943e985f56f14916b40f2dd4a4cbc011d5e29d583ae709c6ae41439e5d75113

test:
  secret_key_base: 984eea1a293f808ecd18a490cf5d43d09ce3f240d05438afc39dfc26b490e7d938d38cc04fabf7f9c02212c90f0affefd9de5944f865f74a828b6c767517635c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
